name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - name: Test
        run: go test -race -timeout 30m -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
  release:
    needs: [ test ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - run: make install-release-tool new-patch-release
